namespace: dev
app: fe-home-bar

datadog:
  env: dev
  service: fe-homebar

deployment:
  name: fe-home-bar-deployment
  replicas: 1

image:
  repository: ghcr.io/utikpuhlik/fe-home-bar
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  name: fe-home-bar-svc
  port: 80

resources:
  requests:
    memory: '32Mi'
    cpu: '25m'
  limits:
    memory: '32Mi'
    cpu: '50m'

secrets:
  api_utils: api-utils-secret
  home_bar: be-home-bar-secret

imagePullSecrets:
  name: ghcr-secret

ingress:
  enabled: true
  name: fe-home-bar-ingressroute
  className: traefik
  host: bar.eucalytics.uk
  annotations: { }
