exclude = { glob = [".idea/**", ".next/**", "target/**", "dist/**", "node_modules/**"] }

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-executables-have-shebangs" },
    { id = "check-illegal-windows-names" },
    { id = "check-case-conflict" },
    { id = "check-ast" },
    { id = "check-json" },
    { id = "check-toml" },
    { id = "check-yaml", exclude = "^(chart|k8s)/templates/" },
    { id = "debug-statements" },
    { id = "end-of-file-fixer" },
    { id = "mixed-line-ending", args = ["--fix=lf"] },
    { id = "fix-byte-order-marker" },
    { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/hadolint/hadolint"
rev = "v2.12.0"
hooks = [
    { id = "hadolint-docker" },
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.3.0"
hooks = [
    { id = "gitleaks" },
]

[[repos]]
repo = "https://github.com/biomejs/pre-commit"
rev = "v2.4.7"
hooks = [
    { id = "biome-check" },
]
