apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.certificate.name}}
  namespace: {{.Values.namespace}}
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  # Secret names are always required.
  secretName: {{.Values.certificate.secretName}}
  issuerRef:
    name: {{ .Values.certificate.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
