apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Values.ingress.name}}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: dev
      services:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Values.certificate.secretName }}